# Generated by Django 5.1.5 on 2025-01-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qtube', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
