# Generated by Django 5.1.5 on 2025-01-27 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qtube', '0002_video_processing_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
