services:
  app:
    container_name: app
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn core.wsgi:application -c gunicorn_config.conf"

    volumes:
      - .:/code/back/
    ports:
      - "8002:8002"
    networks:
      - main
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Tehran
    restart: on-failure

  redis:
    container_name: docker.arvancloud.ir/redis
    image: redis:7.2
    ports:
      - "6379:3679"
    restart: on-failure
    environment:
      - TZ=Asia/Tehran
    networks:
      - main




networks:
  main:
